[variables]
DJANGO_SETTINGS_MODULE = "auth_service.settings.railway"
PYTHONPATH = "."

[phases.build]
cmds = [
    "pip install -r requirements.txt"
]

[start]
cmd = "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn auth_service.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 60"