[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "python312Packages.setuptools", "gcc", "postgresql"]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip",
    "python -m pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "python manage.py collectstatic --noinput"
]

[start]
cmd = "chmod +x start.sh && ./start.sh"

[variables]
PYTHONPATH = "/app"
DJANGO_SETTINGS_MODULE = "auth_service.settings.prod"
PORT = "8000"
