[variables]
DJANGO_SETTINGS_MODULE = "auth_service.settings.prod"
PYTHONPATH = "."
NIXPACKS_PYTHON_VERSION = "3.12"

[phases.build]
cmds = [
    "pip install -r requirements.txt",
    "python manage.py collectstatic --noinput --clear"
]

[start]
cmd = "python manage.py migrate && gunicorn auth_service.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 60"